import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "layout",
	description: "Generated by create next app",
	keywords: ["keyword1", "keyword2", "keyword3"],
};

export default function Layout({ children }: { children: React.ReactNode }) {
	return (
		<div className=" flex flex-col gap-4 p-10">
			<div className="container mx-auto bg-red-900 text-fuchsia-100 font-bold justify-center items-center flex p-4">
				Layout
			</div>
			<div className="border-t border-zinc-800 py-4">{children}</div>
		</div>
	);
}
